version: "3"

services: 
    web:
        build: 
            context: .
        ports: 
            - "8000:8000"
        volumes: 
            - ./bookstore:/bookstore
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on: 
            - redis
    
    redis:
        image: "redis:alpine"

    celery:
        build: .
        command: >
            sh -c  "celery -A bookstore worker --loglevel=info"
        volumes: 
            - ./bookstore:/bookstore
        depends_on: 
            - redis

    celery-beat:
        build: .
        command: >
            sh -c  "celery -A bookstore beat -l info -S django"
        volumes: 
            - ./bookstore:/bookstore
        depends_on: 
            - redis



